services:
  glpi:
    image: "glpi/glpi:11"
    restart: "unless-stopped"
    volumes:
      - "glpi_data:/var/glpi:rw"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - glpi_network

  db:
    image: "mysql:latest"
    restart: "unless-stopped"
    volumes:
      - "glpi_mysql_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${GLPI_DB_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - glpi_network

volumes:
  glpi_data:
  glpi_mysql_data:

networks:
  glpi_network:
